test: skip tracing_multi_* objects due to unsatisfied references
This causes errors like:

```
elf_reader_test.go:1210: Error during loading: program test_fentry_s:
  Call at insn 2: symbol "tracing_multi_arg_check": unsatisfied program reference
```

These are 'linked skeletons' in the selftests dir. Not sure if the build
produces linked objects as well, but these need to be excluded for now.

Signed-off-by: Timo Beckers <timo@isovalent.com>