cmd/bpf2go: clarify -target usage with bpf_tracing.h
Using tracing macros like PT_REGS_PARM1 causes an error when compiling for
generic targets bpf, bpfel and bpfeb:

    offcpu.c:33:41: error: The eBPF is using target specific macros, please provide -target

This is confusing if the user already provides "-target bpfel" or similar.
Clarify that specific arch has to be selected for tracing to work.